### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by rexim** [tsoding/conwhy#9]
- ~Blocked by #3~
- ~Blocked by #12~

It's probably not compilable on Windows. We need to check that.

**Comment by ForNeVeR** [comment]
I could check that.

**Comment by rexim** [comment]
@ForNeVeR thank you very much! Please wait until I merge the latest changes from #3. I'm gonna do that in like 0.5-1h.

**Comment by ForNeVeR** [comment]
Affirmative.

**Comment by rexim** [comment]
I stole this part

https://github.com/tsoding/conwhy/blob/e056867f52b60cadd445c4b5f7ba6548e987aa90/conwhy/conwhy.fsproj#L33

from

https://github.com/codingteam/naggum/blob/0f14714a1dcecc4abb4bdfe77831202f82be582c/Naggum.Backend/Naggum.Backend.fsproj#L51

But I didn't do that `When Condition="'$(VisualStudioVersion)' == '11.0'"` above, because I didn't need that on NixOS. That's why I have concerns that it might not compile on Windows.

Hope that helps.

**Comment by ForNeVeR** [comment]
I believe it should work. That `fsproj` was generated a log ago with a shitty VS project generator that tried (unsuccessfully at every instance I'm aware) to support multiple VS versions. That's nothing more than a historical artifact and will likely be cleaned up eventually.

**Comment by ForNeVeR** [comment]
After small changes, I observe this:

![image](https://user-images.githubusercontent.com/92793/34664170-2c71f4e8-f48d-11e7-8a1c-c14f82b375dc.png)

Does it mean conwhy works?

**Comment by rexim** [comment]
@ForNeVeR yep! That's exactly how it supposed to work until we integrated the logic of the game with Monogame #11

**Comment by ForNeVeR** [comment]
Okay. I'm ready to send a PR with small build changes and instructions after #12 is resolved.

**Comment by rexim** [comment]
Fixed by #13 I guess
